### ISSUE TITLE
[Linux] colorpicker is not working on wayland.

### ISSUE THREAD

**Issue by darkRaspberry** [Toinane/colorpicker#106]
**Describe the bug**
Not working in wayland.

###### Sorry for deleting the template.

Now many distributions are moving from `xorg` to `wayland`. And Ubuntu (my current machine) is also moved to `wayland` by default. So its the ill effect of `wayland` and now colorpicker is not working. Like completely not working.

Its just showing white color nothing else.

**Comment by Toinane** [comment]
Hey @darkRaspberry thank you for reporting this issue! How did you download Colorpicker? from snapstore, .deb file, other..?

**Comment by darkRaspberry** [comment]
> How did you download Colorpicker?

From your website I redirect here https://github.com/Toinane/colorpicker/releases/tag/2.0.3
I tried `.AppImage` and `.deb`. 

Also I expected this when i was installing. Any app which works on something which require reading from screen like screen recorder or screenshot doesn't support wayland directly. Xorg and wayland is not compatible.

**Comment by Toinane** [comment]
Okay I see! I'm sorry for that. I'm a newbie on Linux so I don't know everything about it. I'll try to add wayland compatibility for the next update 👍

**Comment by darkRaspberry** [comment]
See the fact that you are using electron 9.x.x May be is the cause
There is native wayland support by passing the flag in `electron 12` which might be seems mature till now.(As release much earlier)
There is native support in it. https://www.reddit.com/r/linux/comments/lw7cvk/electron_12_has_just_been_released_with_wayland/
This thread seems little worth to see.

FurtherYou can make these options your default for all Electron apps by adding the following into your ~/.config/electron-flags.conf.
```
--enable-features=UseOzonePlatform
--ozone-platform=wayland
```
In dead simple words wayland handles frontend of the linux distro. And IF you app doesn't support wayland or build on wayland. They they can't read from it. But still display on the screen.

Default site- https://wayland.freedesktop.org/
--------------------
Some useless discussion about wayland.
https://github.com/microsoft/vscode/issues/109176

**Comment by Toinane** [comment]
Oh okay thank you for the update! I really appreciate 👍 I'll update Colorpicker for Electron 16 and test the flag on it. I'm sorry for the seriously delay I have on this.

**Comment by darkRaspberry** [comment]
@Toinane No need to say sorry. Instead I'm grateful that you made this cool awesome app.

**Comment by niphoneua** [comment]
@Toinane Please update the snap

**Comment by Toinane** [comment]
Hey @niphoneua sorry, I'm actually working to rewrite all the app and it's take time, so when it's done, I'll update it. I don't know for the moment if the picker will work on Wayland, but I'll do my best to do it 👍

**Comment by niphoneua** [comment]
Thanks

**Comment by step4wd** [comment]
Waiting for the update. Ubuntu 22.04 is out and the App is not working on it maybe because of the Wayland issue

**Comment by Toinane** [comment]
Hey there! Thanks for your waiting! I'm really sorry for the issue I've released a new version with the latest Electron version. It sould work now again on Wayland, I've tried on Ubuntu 22.04 and looks fine. The only issue is the picker feature will not work on Wayland. I can't find a deps for picking color on screen compatible with wayland and nodejs and the only one I use is not maintained for now.

When I can, I'll switch from Electron to Tauri and use Rust deps to make this work again and to be more stable/efficient!

**Comment by step4wd** [comment]
Thank you! Tried the DEB version of 2.1.0 and unfortunately it is still unable to pick colours

![image](https://user-images.githubusercontent.com/2865249/169011624-54bfe405-4f29-45b3-8fd1-5fb124780bb9.png)

**Comment by Toinane** [comment]
If you are in Wayland interface, it's normal yeah, It only work on x11 :/
I'll need to wait a little more the transition on Rust for wayland

**Comment by darkRaspberry** [comment]
Before logging in, If you can change the session from `wayland` to `xorg`. Then it will work as perfect.

Adding `wayland` support to this app takes time. Please wait! This is open-source app, Toinane may fix it when he has time, keep patience.

**Comment by Toinane** [comment]
> Before logging in, If you can change the session from `wayland` to `xorg`. Then it will work as perfect.
> 
> Adding `wayland` support to this app takes time. Please wait! This is open-source app, Toinane may fix it when he has time, keep patience.

Even the picker is a native C++ module? I think this option only work for launching the electron app, right?

**Comment by Toinane** [comment]
![image](https://user-images.githubusercontent.com/7584391/169019138-811f4439-d202-4caa-8326-d5bebc057822.png)
Looks to be working with tauri more easely than I was thinking!

**Comment by nyjsnl** [comment]
Dude, take a look at the color picker I wrote and give me some advice

**Comment by dCo3lh0** [comment]
> Yeah I have the same on Ubuntu GNOME Wayland. Snap doesn't do anything.
> 
> Below error is from AppImage
> 
> ![Screenshot from 2023-10-31 02-35-56](https://private-user-images.githubusercontent.com/9360410/279343690-4170476c-aa4f-4576-8989-3469579337ea.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM0MzU2ODcsIm5iZiI6MTczMzQzNTM4NywicGF0aCI6Ii85MzYwNDEwLzI3OTM0MzY5MC00MTcwNDc2Yy1hYTRmLTQ1NzYtODk4OS0zNDY5NTc5MzM3ZWEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTIwNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEyMDVUMjE0OTQ3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MDliMTRhYWI2YWZiZmViZjgwNjAwYmU3YThkZjg3NzYxZGRhMTE1ODk1ZTU4NzJjYzY3YzY1NWRiYTUxMTQ4NSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.W4dlmBkyLu-J-tKM2Kr60gWEmVRK4NFxBpEH9oq5JME)

having this same error

**Comment by Toinane** [comment]
Got it, I've started to rewrite c++ module to fix some issues like this one, I need to take time to continue on this rewrite

**Comment by GogoFC** [comment]
> Got it, I've started to rewrite c++ module to fix some issues like this one, I need to take time to continue on this rewrite

Hello. I thought you already fixed this because it works fine now. :)
